### ISSUE TITLE
@BeanParam TaskForm is null on WildFly

### ISSUE THREAD

**Issue by fmarchioni** [hantsy/jakartaee-mvc-sample#1]
When deploying the application on the latest version of WildFly (21) the @BeanParam receives null values for the form fields.

To Reproduce the issue, deploy the application on WildFly 21 and add a new Task.

When you add the Task, the following error is reported:
```
<violationReport>
   <parameterViolations>
      <constraintType>PARAMETER</constraintType>
      <path>save.arg0.name</path>
      <message>must not be blank</message>
      <value/>
   </parameterViolations>
   <parameterViolations>
      <constraintType>PARAMETER</constraintType>
      <path>save.arg0.description</path>
      <message>must not be blank</message>
      <value/>
   </parameterViolations>
</violationReport>
```

If you remove the validation from the method:
` public Response save(@Valid @BeanParam TaskForm form)`
..you will see that the 'form' parameter gets injected a null.
 
I hope you can shed some light on this issue and maybe suggest a workaround/solution.

**Comment by hantsy** [comment]
Did you follow the readme to deploy on Wildfly?

```bash 
mvn clean wildfly:run -Pwildfly
```

**Comment by fmarchioni** [comment]
Thanks @hantsy I've got it.
I've seen the 'wildfly' profile includes in WEB-INF/lib also the krazo-resteasy-1.0.0.jar which is (as I understand) the 'glue' between JAX-RS and MVC. Now it works. Thanks, I'll close the issue
